export const FETCH_PERSONS_START = 'FETCH_PERSONS_START';
export const FETCH_PERSONS = 'FETCH_PERSONS';
export const FETCH_PERSONS_SUCCESS = 'FETCH_PERSONS_SUCCESS';
export const FETCH_PERSONS_FAILED = 'FETCH_PERSONS_FAILED';

export const SELECT_PERSON_SUCCESS = 'SELECT_PERSON_SUCCESS';